### ISSUE TITLE
Replace the about section in the home page

### ISSUE THREAD

**Issue by VinayakFia** [CSESoc-CompClub/learn#2]
## Task
Rewrite the heading and content of the about section of the website. Mention the following:
- [ ] What compclub is
- [ ] What compclub learn is and who its for
- [ ] Link to compclub main website somewhere

Be creative!

## Current
<img width="648" alt="image" src="https://github.com/CSESoc-CompClub/learn/assets/96902642/851dabac-92d1-49fc-9742-6868678bbc21">
