### ISSUE TITLE
Contact us section

### ISSUE THREAD

**Issue by VinayakFia** [CSESoc-CompClub/learn#6]
## Task
<img width="625" alt="image" src="https://github.com/CSESoc-CompClub/learn/assets/96902642/ee12a5d4-73a2-4664-89ac-e165e527bead">

- [ ] reword the lets connect section to make it suitable for compclub
- [ ] link our main website
- [ ] link our github
- [ ] link our facebook
- [ ] replace trevors email with contact@compclub.org
